Draft of HW Instancing Test Plan
o3de/sig-graphics-audio pull request #126
Opened 2023-03-07 20:08 UTC by smurly

2023-03-09 18:20 UTC, jromnoa requested changes

2023-03-09 18:20 UTC, jromnoa commented on testing-guidance/Test-Plan_-Atom-HW-Instancing.md
> +**Scene Testing:** System integration tests will be run against predetermined scenes with known content to determin performance impact from frame time measurements.
typo: `determin`

2023-03-09 18:20 UTC, jromnoa commented on testing-guidance/Test-Plan_-Atom-HW-Instancing.md
> +- Creation of an Editor Python Bindings (hydra) test automation case in AutomatedTesting project
we should stop using old internal names like `hydra` i think
there is old code that still uses it but we should remove all hydra references and just call them Editor Python Bindings

you could maybe mention the buses if you want to be more specific, but we should stop using the `hydra` term going forward

2023-03-09 18:20 UTC, jromnoa commented on testing-guidance/Test-Plan_-Atom-HW-Instancing.md
> +*   Editor Python Bindings (hydra) test
`hydra` reference should be removed

2023-03-09 18:20 UTC, jromnoa commented on testing-guidance/Test-Plan_-Atom-HW-Instancing.md
> +*   Python Editor Bindings (hydra) automation case to ensure instanced draw calls are correct
`hydra` reference should be removed

2023-03-09 18:20 UTC, jromnoa commented on testing-guidance/Test-Plan_-Atom-HW-Instancing.md
> +| Risk                                                                                                                                   | Mitigation
is there a location that lists all of the Impact/Likelihood/Risk Level scales? I'm not sure how much more severe `14 - medium` is to `2 - negligible` without knowing the full scale
same for the other sections, I can't get a grasp of the valuation for each category without knowing the full scale (1-10? 1-100? etc.)

2023-03-09 18:20 UTC, jromnoa commented on testing-guidance/Test-Plan_-Atom-HW-Instancing.md
> +| Splitting implementation may mean that we don't see full scope of impact to other platforms and performance                            | Consider disabling HW instancing on platforms not specifical
Notes/Impact/Likelihood/Risk Level blank for the first Risk about splitting implementation

2023-03-09 19:23 UTC, smurly commented on testing-guidance/Test-Plan_-Atom-HW-Instancing.md
> +| Risk                                                                                                                                   | Mitigation
these are from a risk assessment matrix where something like impact * likelihood = risk. larger numbers are bad and generally need to be mitigated to the likelihood of `eliminated`
https://en.wikipedia.org/wiki/Risk_matrix

2023-03-09 19:25 UTC, smurly commented on testing-guidance/Test-Plan_-Atom-HW-Instancing.md
> +| Splitting implementation may mean that we don't see full scope of impact to other platforms and performance                            | Consider disabling HW instancing on platforms not specifical
unknown-unknown 🤷🏼‍♂️ maybe that's super high risk

2023-03-09 20:01 UTC, amzn-tommy commented on testing-guidance/Test-Plan_-Atom-HW-Instancing.md
> +
Worth calling out that for phase 2, and important test item is:

A level with 3 mesh components that each have the same model + material combination, meaning they are instance-able. The should each have the 'Use Forward Pass IBL' setting set to true on the mesh component (or test on mobile where forward pass IBL is used for all meshes, regardless of the component setting). There should be two reflection probes in the level. 2 of the 3 mesh components should be near one probe, and the other should be near the other probe. This should result in 2 draw calls in the main view, since the 3rd mesh that is near a different reflection probe cannot be instanced with the other two. Functionally, the reflections should be the same with and without instancing enabled.

2023-03-14 19:44 UTC, amzn-tommy commented on testing-guidance/Test-Plan_-Atom-HW-Instancing.md
> +*   `r_enableMeshInstancing` enabled and disabled
This has actually changed to r_meshInstancingEnabled

2023-03-14 19:44 UTC, amzn-tommy approved these changes

2023-03-14 21:03 UTC, merged