Added RFC for Compute Shader support
o3de/sig-graphics-audio pull request #167
Opened 2024-12-03 16:08 UTC by galibzon

Added RFC for Compute Shader support

2024-12-05 10:38 UTC, kh-huawei requested changes
I generally support this RFC: having the option to use the Material-Shaders in a compute shader makes everything more flexible, and if we get nothing else, this is a good start.

But for this to be really useful, it would need to be a bit more flexible with the mip-level selection, and at least somehow support indirect dispatch.

And most features that would use this also need access to the geometry of multiple objects, but for that we also need RFC https://github.com/o3de/sig-graphics-audio/issues/152.

2024-12-05 10:38 UTC, kh-huawei commented on rfcs/MaterialComputeShader/RFC_MaterialWithComputeShaders.md
> +        "SAMPLE_LEVEL_LOD=0"
To re-iterate the comment from @msat-huawei from the related PR: Hardcoding the sample level seems limiting. It would be better to use a define without value to switch the behavior, and keep the level selection separate.

I'd prefer to use SampleGrad() with hardcoded ddx/ddy=0, to get the same behavior but obvious start points for future changes, but a separate define with a default value if its not defined would work as well.

2024-12-05 10:38 UTC, kh-huawei commented on rfcs/MaterialComputeShader/RFC_MaterialWithComputeShaders.md
> +    VsOutput IN = CalculateVsOutputFromStreamBuffers(dispatch_id.xy);
The Raytracing-Implementation already has to do something similar to get from a Hit to the actual geometry. but the RayTracingSceneSrg provides access to the geometry of all meshes.
Would it be possible to use that functionality, but moved to the MeshFeatureProcessor proper and adapted so it works for compute shaders?
Incidentially, this would also make a deferred pipeline more feasible..,

2024-12-05 10:38 UTC, kh-huawei commented on rfcs/MaterialComputeShader/RFC_MaterialWithComputeShaders.md
> +        virtual DispatchDrawItemList BuildDispatchDrawItemList(
How would this work with indirect dispatch? _Could_ this work with indirect dispatch in a similar manner, or would this need a separate interface somewhere?

2024-12-05 10:38 UTC, kh-huawei commented on rfcs/MaterialComputeShader/RFC_MaterialWithComputeShaders.md
> +This is very important for alternative rendering methods like Texture Space Shading and having fine control
If i understand this correctly, you are creating a compute shader invocation for each (visible) object, but each shader is limited to exactly that object.
I'm not entirely sure if this going to be that useful on its own. At least not for Texture Space Shading, since there you usually need something like a V-Buffer pass, and once you have that, "rendering" each object separately again with a compute shader seems counter-intuitive.

2024-12-05 15:42 UTC, galibzon commented on rfcs/MaterialComputeShader/RFC_MaterialWithComputeShaders.md
> +    VsOutput IN = CalculateVsOutputFromStreamBuffers(dispatch_id.xy);
Yes, it's possible. That's why in the PR I added the classes `ShaderStreamBufferViewsBuilder` and `ShaderStreamBufferViewsBuilderInterface`, which do basically the same labor that the RayTracing code does to Bind Vertex Streams. In the PR I did not change the RayTracing code to use the `ShaderStreamBufferViewsBuilder`  to keep the code review to a minimum.

2024-12-05 15:51 UTC, galibzon commented on rfcs/MaterialComputeShader/RFC_MaterialWithComputeShaders.md
> +This is very important for alternative rendering methods like Texture Space Shading and having fine control
Correct, the case of Texture Space Shading requires custom pipelines for the V-Buffer pass, etc. It is a very unique case, and in this case the Compute Shader runs for each (visible) object and yes, each shader is limited to exactly that object (to be more precise limited to that DrawItem).

It is very useful on its own (We are using it in our internal project), but requires other things like custom V-Buffer pass, etc... BUT the benefit of being able to integrate Compute Shaders with the material system is that we can leverage the material system shader code for lighting, etc.

2024-12-05 15:55 UTC, galibzon commented on rfcs/MaterialComputeShader/RFC_MaterialWithComputeShaders.md
> +        "SAMPLE_LEVEL_LOD=0"
I agree, at the moment seems limiting, but it is just a starting point. Some may prefer SampleLevel(), while other would rather use SampleGrad() and there's nothing to forbid us from adding more macros and let the developer pick what they need.

Very soon in our internal project we'll have to figure out how to work with LOD and we'll provide a new PR for a more flexible to pick the LOD level at runtime or Gradients.

This is not the end of the road, it's just the beginning.

2024-12-06 14:16 UTC, kh-huawei commented on rfcs/MaterialComputeShader/RFC_MaterialWithComputeShaders.md
> +        "SAMPLE_LEVEL_LOD=0"
Fair. 
But, and this somewhat of a nitpick, to keep the impact of future PRs even lower, i would prefer a simple 'CS_SAMPLERS' define now (or so. Names are hard), and hardcode the LOD to 0 in hlsl code, with the implicit understanding that the sampling itself will change, but not the fact that it's sampling in a Compute Shader.

Changing the behavior of an existing define will be a greater impact in the future than adding new ones, especially if other devs already started building on your defines...

2024-12-06 15:51 UTC, galibzon commented on rfcs/MaterialComputeShader/RFC_MaterialWithComputeShaders.md
> +        "SAMPLE_LEVEL_LOD=0"
Sounds good. Will update the PR accordingly. https://github.com/o3de/o3de/pull/18509

2024-12-09 08:36 UTC, kh-huawei approved these changes

2024-12-09 17:33 UTC, moudgils approved these changes
Supportive of this RFC. Thanks for the contribution. Looking forward to seeing the texture space pipeline in future :)

2024-12-09 17:45 UTC, merged