Atom renderer automation strategy document
o3de/sig-graphics-audio pull request #78
Opened 2022-09-30 17:38 UTC by smurly

initial push without image files
Signed-off-by: Scott Murray <scottmur@amazon.com>

2022-09-30 18:34 UTC, jromnoa requested changes

2022-09-30 18:34 UTC, jromnoa commented on testing-guidance/Atom-Automation-Strategy.md
> +We will accomplish this by relying as much as we can on unit tests and utilize Automated Review (AR) through LY\_Test\_Tools (LYTT) for integration tests. By focusing on O3DE wide tooling, we will av
i think its just "LyTestTools" without the underscores

2022-09-30 18:34 UTC, jromnoa commented on testing-guidance/Atom-Automation-Strategy.md
> +Existing samples and test content in ASV should transition to AutomatedTesting where it is more accessible to customers and where it can be added to periodic or gated AR.
Should we include language here that we want to move away from using AtomSampleViewer in the future? not sure if that talk is still in process or confirmed

2022-09-30 18:34 UTC, jromnoa commented on testing-guidance/Atom-Automation-Strategy.md
> +![The Inverted Pyramid](/images/test_automation_pyramid_inverted.png)
image link doesn't work

2022-09-30 18:34 UTC, jromnoa commented on testing-guidance/Atom-Automation-Strategy.md
> +![OpenCPPCoverage VS2019 plugin](/images/OpenCPPCoverage.png)
also broken image link

2022-09-30 18:34 UTC, jromnoa commented on testing-guidance/Atom-Automation-Strategy.md
> +### Python LY\_Test\_Tools (LYTT pytest)
should be LyTestTools, underscores aren't needed

2022-09-30 19:25 UTC, smurly commented on testing-guidance/Atom-Automation-Strategy.md
> +This section provides an overview of our prioritization logic based on the [Test Automation Pyramid](#AtomAutomationStrategy-TestAutomationPyramid) methodology.
these are images and lfs isn't enabled for this repo. I have to add them with a web editor to github somewhere

2022-09-30 19:27 UTC, smurly commented on testing-guidance/Atom-Automation-Strategy.md
> +Existing samples and test content in ASV should transition to AutomatedTesting where it is more accessible to customers and where it can be added to periodic or gated AR.
They want to retain AtomSampleViewer for development work, so this is really just testing moves to AutomatedTesting project and we don't use ASV for testing

2022-09-30 19:28 UTC, smurly commented on testing-guidance/Atom-Automation-Strategy.md
> +![The Inverted Pyramid](/images/test_automation_pyramid_inverted.png)
lfs not available I'll have to figure out how to get these on github

2022-09-30 20:37 UTC, NeilGitGud requested changes

2022-09-30 20:37 UTC, NeilGitGud commented on testing-guidance/Atom-Automation-Strategy.md
> +
Missing priority

2022-09-30 20:37 UTC, NeilGitGud commented on testing-guidance/Atom-Automation-Strategy.md
> +
Missing priority

2022-09-30 20:37 UTC, NeilGitGud commented on testing-guidance/Atom-Automation-Strategy.md
> +
Missing priority

2022-09-30 20:37 UTC, NeilGitGud commented on testing-guidance/Atom-Automation-Strategy.md
> +
All of these links do nothing for me, are they supposed to jump to the specified section of the document?

2022-09-30 20:52 UTC, smurly commented on testing-guidance/Atom-Automation-Strategy.md
> +#### Expand support for batched test case patterns to include more tooling than just Editor
added more direct mention of Mulittest Framework

2022-09-30 21:49 UTC, NeilGitGud approved these changes

2022-09-30 21:57 UTC, Broganab approved these changes

2022-10-03 20:21 UTC, jromnoa approved these changes

2022-10-04 21:32 UTC, merged