adding editor_skies.md file for LKG updates
o3de/sig-graphics-audio pull request #98
Opened 2023-01-17 18:02 UTC by Broganab

Signed-off-by: Broganab <broganab@amazon.com>

2023-01-17 18:15 UTC, AMZN-Dk commented on testing-guidance/workflow-tests/Lighting_and_Skies/editor_skies.md
> +*   Create new level or open an existing level
Looks like you are using bulleted lists instead of the numbered list and table format which has been the standard for most of these I've reviewed. I would switch to using the numbered list and table format before you get too far along and have to change it all. Example: https://github.com/o3de/sig-graphics-audio/blob/main/testing-guidance/workflow-tests/Decals_and_Cloth/Editor_Decals_and_Cloth_fog_workflow_test.md

2023-01-17 20:44 UTC, NeilGitGud requested changes

2023-01-17 20:44 UTC, NeilGitGud commented on testing-guidance/workflow-tests/Lighting_and_Skies/editor_skies.md
> +
I recommend adding a two more items here about visual appearance, for example:
 - Each material or asset loads properly and has the expected visual impact. For example, no asset load errors when selecting materials or assets, and no assets that appear completely black or obviously distorted when applied to a component
  - When a component settings value is changed, it has a visual impact on the level. The change may be subtle or hard to see at first, but log an issue if no change is present

2023-01-17 21:28 UTC, NeilGitGud commented on testing-guidance/workflow-tests/Lighting_and_Skies/editor_skies.md
> +(repeat steps with different cubemaps, and ground plane mats)
I like this part! leave it open ended and recommend they try other approaches

2023-01-17 21:28 UTC, NeilGitGud commented on testing-guidance/workflow-tests/Lighting_and_Skies/editor_skies.md
> +
add a timebox line here indicating how long the test should take to complete. Also this is a good place to mention that this is just an example workflow and encourage them to try other approaches. You can use the same line I do, just adjust the length of the timebox to fit your test:

Suggested Time Box: 15 minutes per platform. Note that the workflow below is the basic steps, feel free to experiment with other settings during the remaining time.

2023-01-17 21:28 UTC, NeilGitGud commented on testing-guidance/workflow-tests/Lighting_and_Skies/editor_skies.md
> +*   Create new level or open an existing level
Definitely agree with this, the Decals and Cloth workflow that David mentioned is probably closest. You should be able to edit it, and just copy the table formatting from there.

Here is another example just in case: https://github.com/o3de/sig-graphics-audio/blob/main/testing-guidance/workflow-tests/MSAA_and_Deferred_Fog/Editor_SMAA_and_Deferred_fog_workflow_test.md

2023-01-17 21:28 UTC, NeilGitGud commented on testing-guidance/workflow-tests/Lighting_and_Skies/editor_skies.md
> +*   Create new level or open an existing level
Also be sure to include screenshots whenever possible! They are a great way to show an example expected result

2023-01-18 17:27 UTC, Broganab commented on testing-guidance/workflow-tests/Lighting_and_Skies/editor_skies.md
> +
added extra common issues as suggested

2023-01-18 17:33 UTC, Broganab commented on testing-guidance/workflow-tests/Lighting_and_Skies/editor_skies.md
> +
added timebox suggestion

2023-01-18 21:41 UTC, NeilGitGud approved these changes

2023-01-18 22:59 UTC, merged